stages:
    - check

lint:
    stage: check
    image: node:20
    script:
        - npm ci
        - npx prettier --check ./src
        - npx expo customize tsconfig.json
        - npm run get-git-hash
        - npm run tsc
    cache:
        key: npm-${CI_COMMIT_REF_SLUG}
        paths:
            - node_modules/

test:
    stage: check
    image: node:20
    script:
        - npm ci
        - npm run get-git-hash
        - npm run test
    cache:
        key: npm-${CI_COMMIT_REF_SLUG}
        paths:
            - node_modules/
